version: '3'
services: # services which our app going to use. (list of containers we want to create)
  mongo_db: # container name 
    image: mongo:latest # which image container will build on
    container_name: mongoDB
    restart: always
    ports:
      - "27017:27017"
    networks: # adding network
      - mern-app
    volumes:
      - mongo-data:/data/db
    
  app:
    image: milancakic/spass
    container_name: sPASS
    networks: # adding network
      - mern-app
    ports:
      - "0.0.0.0:7000:8080"
    depends_on:
      - mongo_db
    environment:
      - PORT=8080
      - MONGO_URL_DOCKER=mongodb://mongo_db:27017 #default
      - APP_EMAIL_PASSWORD=fqyl uquz zeyx bdkt #register email code for app usage 
      - SESSION_SECRET=SmeSpaginaL45poretal 
      - ENCRYPTION_KEY=rasentimentalisaselitiseosecaji


networks:
  mern-app:
    driver: bridge

volumes: 
  mongo-data:
    driver: local
